//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvalick421.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class phone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public phone()
        {
            this.type_defect = new HashSet<type_defect>();
        }
    
        public int id_phone { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public Nullable<int> id_phone_type { get; set; }
        public Nullable<int> id_type_defect { get; set; }
    
        public virtual phone_type phone_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<type_defect> type_defect { get; set; }
    }
}
