//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvalick421.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id_Purchase { get; set; }
        public string Name { get; set; }
        public string Amount { get; set; }
    }
}
