//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kvalick421.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class type_defect
    {
        public int id_type_defect { get; set; }
        public string Name { get; set; }
        public Nullable<int> id_phone { get; set; }
    
        public virtual phone phone { get; set; }
    }
}
